name: Deploy to Dev

on:
  push:
    branches:
      ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grand gradlew execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle clean build
        run: ./gradlew clean bootJar

      # Docker Image Build
      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gbgokgok-api .

      # Login to DockerHub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push to DockerHub
      - name: DockerHub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gbgokgok-api

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gbgokgok-api
            docker stop gbgokgok-api || true
            docker rm gbgokgok-api || true
            docker run -d --restart unless-stopped -p 8080:8080 --name gbgokgok-api ${{ secrets.DOCKERHUB_USERNAME }}/gbgokgok-api
            docker image prune -f